### ISSUE TITLE
NoteIntents is not found

### ISSUE THREAD

**Issue by c19354837** [wahdatjan/react-native-common-intents#2]
[NoteIntents](https://github.com/wahdatjan/react-native-common-intents/blob/master/android/src/main/java/com/wahdatjan/intents/IntentModule.java#L151) will cause a compiling fail.

`NoteIntents` is not a standard API in Android SDK. You can find it in `com.google.android.gms:play-services-base`.

**Comment by wahdatjan** [comment]
did it fail for you while compiling? 

> [NoteIntents](https://github.com/wahdatjan/react-native-common-intents/blob/master/android/src/main/java/com/wahdatjan/intents/IntentModule.java#L151) will cause a compiling fail.
> 
> `NoteIntents` is not a standard API in Android SDK. You can find it in `com.google.android.gms:play-services-base`.
